amcl:
  ros__parameters:
    use_sim_time: false
    min_particles: 500
    max_particles: 2000
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    scan_topic: "scan"

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: "/home/junhyuk/ros2_ws/src/MATRO_NB/maps/map.yaml"

planner_server:
  ros__parameters:
    expected_planner_frequency: 1.0

controller_server:
  ros__parameters:
    controller_frequency: 10.0
